### ISSUE TITLE
Fix double website building+deployment

### ISSUE THREAD

**Issue by marvinschmitt** [bayesflow-org/awesome-amortized-inference#18]
Currently, the GitHub Pages Action builds the website after each commit -- that means once after the manual (human) commit and then after the bot builds the README. The first build should be suppressed.

Probably best done by manually building with a GH Action instead of using the pre-configured pages build from GH Settings

**Comment by vpratz** [comment]
Seems to be fixed with the current settings and actions. Please reopen if I misinterpreted something.
